import mongoose from "mongoose";

//User Schema
const UserSchema = mongoose.Schema(
    {
        types:{
           type:String,
        },
        firstName:{
            type:String,
            required:true
        },
        lastName:{
            type:String,
            default:""
        },
        email:{
            type:String,
            required:true,
            unique:true
        },
        phoneNumber:{
            type:Number,
            required:true,
            unique:true
        },
        password:{
            type:String,
            default:""
        },
        companyName:{
            type:String,
            required:true
        },
        address1:{
            type:String,
            required:true
        },
        address2:{
            type:String,
            default:""
        },
        city:{
            type:String,
            required:true 
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        zipCode:{
            type:Number,
            required:true
        },
        skype:{
            type:String,
            required:true
        },
        trafficSource:{
            type:String,
            default:""
        },
        experience:{
            type:String,
            default:""
        },
        hearAbout:{
            type:String,
            required:true
        },
        currentlyPromote: {
            type:String,
            default:""
        },
        isMember:{
            type:Boolean,
            default:""
        },
        signed:{
            type:String,
            default:""
        },
        isAgree:{
            type:Boolean,
            default:""
        },
        siteUrl:{
            type:String,
            default:""
        },
        description:{
            type:String,
            default:""
        }
    },
    {timestamps:true}
);

// User Model
const UserModel = mongoose.model("users", UserSchema);
export default UserModel;